/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as TransactionsImportsRouteImport } from './routes/transactions/imports'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as AssetsImportsRouteImport } from './routes/assets/imports'
import { Route as TransactionsImportsIdRouteImport } from './routes/transactions/imports.$id'
import { Route as AssetsImportsIdRouteImport } from './routes/assets/imports.$id'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsImportsRoute = TransactionsImportsRouteImport.update({
  id: '/transactions/imports',
  path: '/transactions/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsImportsRoute = AssetsImportsRouteImport.update({
  id: '/assets/imports',
  path: '/assets/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsImportsIdRoute = TransactionsImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransactionsImportsRoute,
} as any)
const AssetsImportsIdRoute = AssetsImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsImportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/assets/imports': typeof AssetsImportsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/transactions/imports': typeof TransactionsImportsRouteWithChildren
  '/assets': typeof AssetsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/assets/imports/$id': typeof AssetsImportsIdRoute
  '/transactions/imports/$id': typeof TransactionsImportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/assets/imports': typeof AssetsImportsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/transactions/imports': typeof TransactionsImportsRouteWithChildren
  '/assets': typeof AssetsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/assets/imports/$id': typeof AssetsImportsIdRoute
  '/transactions/imports/$id': typeof TransactionsImportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/assets/imports': typeof AssetsImportsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/transactions/imports': typeof TransactionsImportsRouteWithChildren
  '/assets/': typeof AssetsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/assets/imports/$id': typeof AssetsImportsIdRoute
  '/transactions/imports/$id': typeof TransactionsImportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/assets/imports'
    | '/settings/account'
    | '/transactions/imports'
    | '/assets'
    | '/transactions'
    | '/assets/imports/$id'
    | '/transactions/imports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/assets/imports'
    | '/settings/account'
    | '/transactions/imports'
    | '/assets'
    | '/transactions'
    | '/assets/imports/$id'
    | '/transactions/imports/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/assets/imports'
    | '/settings/account'
    | '/transactions/imports'
    | '/assets/'
    | '/transactions/'
    | '/assets/imports/$id'
    | '/transactions/imports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
  AssetsImportsRoute: typeof AssetsImportsRouteWithChildren
  SettingsAccountRoute: typeof SettingsAccountRoute
  TransactionsImportsRoute: typeof TransactionsImportsRouteWithChildren
  AssetsIndexRoute: typeof AssetsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/imports': {
      id: '/transactions/imports'
      path: '/transactions/imports'
      fullPath: '/transactions/imports'
      preLoaderRoute: typeof TransactionsImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/imports': {
      id: '/assets/imports'
      path: '/assets/imports'
      fullPath: '/assets/imports'
      preLoaderRoute: typeof AssetsImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/imports/$id': {
      id: '/transactions/imports/$id'
      path: '/$id'
      fullPath: '/transactions/imports/$id'
      preLoaderRoute: typeof TransactionsImportsIdRouteImport
      parentRoute: typeof TransactionsImportsRoute
    }
    '/assets/imports/$id': {
      id: '/assets/imports/$id'
      path: '/$id'
      fullPath: '/assets/imports/$id'
      preLoaderRoute: typeof AssetsImportsIdRouteImport
      parentRoute: typeof AssetsImportsRoute
    }
  }
}

interface AssetsImportsRouteChildren {
  AssetsImportsIdRoute: typeof AssetsImportsIdRoute
}

const AssetsImportsRouteChildren: AssetsImportsRouteChildren = {
  AssetsImportsIdRoute: AssetsImportsIdRoute,
}

const AssetsImportsRouteWithChildren = AssetsImportsRoute._addFileChildren(
  AssetsImportsRouteChildren,
)

interface TransactionsImportsRouteChildren {
  TransactionsImportsIdRoute: typeof TransactionsImportsIdRoute
}

const TransactionsImportsRouteChildren: TransactionsImportsRouteChildren = {
  TransactionsImportsIdRoute: TransactionsImportsIdRoute,
}

const TransactionsImportsRouteWithChildren =
  TransactionsImportsRoute._addFileChildren(TransactionsImportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
  AssetsImportsRoute: AssetsImportsRouteWithChildren,
  SettingsAccountRoute: SettingsAccountRoute,
  TransactionsImportsRoute: TransactionsImportsRouteWithChildren,
  AssetsIndexRoute: AssetsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
