/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppBudgetsIndexRouteImport } from './routes/_app/budgets/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppTransactionsAllRouteImport } from './routes/_app/transactions/all'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppAssetsImportsRouteImport } from './routes/_app/assets/imports'
import { Route as AppTransactionsImportsIndexRouteImport } from './routes/_app/transactions/imports/index'
import { Route as AppTransactionsImportsIdRouteImport } from './routes/_app/transactions/imports/$id'
import { Route as AppAssetsImportsIdRouteImport } from './routes/_app/assets/imports.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsAllRoute = AppTransactionsAllRouteImport.update({
  id: '/transactions/all',
  path: '/transactions/all',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsImportsRoute = AppAssetsImportsRouteImport.update({
  id: '/assets/imports',
  path: '/assets/imports',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsImportsIndexRoute =
  AppTransactionsImportsIndexRouteImport.update({
    id: '/transactions/imports/',
    path: '/transactions/imports/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransactionsImportsIdRoute =
  AppTransactionsImportsIdRouteImport.update({
    id: '/transactions/imports/$id',
    path: '/transactions/imports/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAssetsImportsIdRoute = AppAssetsImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsImportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/agent': typeof AppAgentRoute
  '/dashboard': typeof AppDashboardRoute
  '/': typeof AppIndexRoute
  '/assets/imports': typeof AppAssetsImportsRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/transactions/all': typeof AppTransactionsAllRoute
  '/assets': typeof AppAssetsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/assets/imports/$id': typeof AppAssetsImportsIdRoute
  '/transactions/imports/$id': typeof AppTransactionsImportsIdRoute
  '/transactions/imports': typeof AppTransactionsImportsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/agent': typeof AppAgentRoute
  '/dashboard': typeof AppDashboardRoute
  '/': typeof AppIndexRoute
  '/assets/imports': typeof AppAssetsImportsRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/transactions/all': typeof AppTransactionsAllRoute
  '/assets': typeof AppAssetsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/assets/imports/$id': typeof AppAssetsImportsIdRoute
  '/transactions/imports/$id': typeof AppTransactionsImportsIdRoute
  '/transactions/imports': typeof AppTransactionsImportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/imports': typeof AppAssetsImportsRouteWithChildren
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/transactions/all': typeof AppTransactionsAllRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/assets/imports/$id': typeof AppAssetsImportsIdRoute
  '/_app/transactions/imports/$id': typeof AppTransactionsImportsIdRoute
  '/_app/transactions/imports/': typeof AppTransactionsImportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/accounts'
    | '/agent'
    | '/dashboard'
    | '/'
    | '/assets/imports'
    | '/settings/account'
    | '/transactions/all'
    | '/assets'
    | '/budgets'
    | '/transactions'
    | '/assets/imports/$id'
    | '/transactions/imports/$id'
    | '/transactions/imports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/agent'
    | '/dashboard'
    | '/'
    | '/assets/imports'
    | '/settings/account'
    | '/transactions/all'
    | '/assets'
    | '/budgets'
    | '/transactions'
    | '/assets/imports/$id'
    | '/transactions/imports/$id'
    | '/transactions/imports'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/accounts'
    | '/_app/agent'
    | '/_app/dashboard'
    | '/_app/'
    | '/_app/assets/imports'
    | '/_app/settings/account'
    | '/_app/transactions/all'
    | '/_app/assets/'
    | '/_app/budgets/'
    | '/_app/transactions/'
    | '/_app/assets/imports/$id'
    | '/_app/transactions/imports/$id'
    | '/_app/transactions/imports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/all': {
      id: '/_app/transactions/all'
      path: '/transactions/all'
      fullPath: '/transactions/all'
      preLoaderRoute: typeof AppTransactionsAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/imports': {
      id: '/_app/assets/imports'
      path: '/assets/imports'
      fullPath: '/assets/imports'
      preLoaderRoute: typeof AppAssetsImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/imports/': {
      id: '/_app/transactions/imports/'
      path: '/transactions/imports'
      fullPath: '/transactions/imports'
      preLoaderRoute: typeof AppTransactionsImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/imports/$id': {
      id: '/_app/transactions/imports/$id'
      path: '/transactions/imports/$id'
      fullPath: '/transactions/imports/$id'
      preLoaderRoute: typeof AppTransactionsImportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/imports/$id': {
      id: '/_app/assets/imports/$id'
      path: '/$id'
      fullPath: '/assets/imports/$id'
      preLoaderRoute: typeof AppAssetsImportsIdRouteImport
      parentRoute: typeof AppAssetsImportsRoute
    }
  }
}

interface AppAssetsImportsRouteChildren {
  AppAssetsImportsIdRoute: typeof AppAssetsImportsIdRoute
}

const AppAssetsImportsRouteChildren: AppAssetsImportsRouteChildren = {
  AppAssetsImportsIdRoute: AppAssetsImportsIdRoute,
}

const AppAssetsImportsRouteWithChildren =
  AppAssetsImportsRoute._addFileChildren(AppAssetsImportsRouteChildren)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAgentRoute: typeof AppAgentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsImportsRoute: typeof AppAssetsImportsRouteWithChildren
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppTransactionsAllRoute: typeof AppTransactionsAllRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransactionsImportsIdRoute: typeof AppTransactionsImportsIdRoute
  AppTransactionsImportsIndexRoute: typeof AppTransactionsImportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAgentRoute: AppAgentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsImportsRoute: AppAssetsImportsRouteWithChildren,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppTransactionsAllRoute: AppTransactionsAllRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransactionsImportsIdRoute: AppTransactionsImportsIdRoute,
  AppTransactionsImportsIndexRoute: AppTransactionsImportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
