import { Transaction } from "./columns";

// Helper function to generate date string in format "YYYY-MM-DD HH:MM:SS"
function createTimestamp(
  year: number,
  month: number,
  day: number,
  hour: number = 12,
  minute: number = 0,
): string {
  const monthStr = String(month).padStart(2, "0");
  const dayStr = String(day).padStart(2, "0");
  const hourStr = String(hour).padStart(2, "0");
  const minuteStr = String(minute).padStart(2, "0");
  return `${year}-${monthStr}-${dayStr} ${hourStr}:${minuteStr}:00`;
}

// Generate sample transactions spanning the last 3-4 months
// Current date context: January 2025
export const sampleTransactions: Transaction[] = [
  // January 2025 - Income
  {
    id: "txn-001",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 15, 9, 0),
    name: "Salary Deposit",
    currency: "GBP",
    amount: 3500.0,
    category: "Other",
    reference: "SAL-2025-001",
    notes: "Monthly salary",
  },
  {
    id: "txn-002",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 10, 14, 30),
    name: "Freelance Payment",
    currency: "USD",
    amount: 1200.0,
    category: "Other",
    reference: "INV-2025-001",
    notes: "Web development project",
  },
  {
    id: "txn-003",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 5, 11, 15),
    name: "Consulting Fee",
    currency: "GBP",
    amount: 800.0,
    category: "Other",
    reference: "INV-2025-002",
    notes: "Business consulting",
  },

  // January 2025 - Food Expenses
  {
    id: "txn-004",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 15, 8, 30),
    name: "Starbucks Coffee",
    currency: "GBP",
    amount: -4.5,
    category: "Food",
    reference: "TXN-2025-001",
    notes: "Morning coffee",
  },
  {
    id: "txn-005",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 14, 18, 0),
    name: "Restaurant Dinner",
    currency: "GBP",
    amount: -85.0,
    category: "Food",
    reference: "TXN-2025-002",
    notes: "Dinner with friends",
  },
  {
    id: "txn-006",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 13, 19, 30),
    name: "Uber Eats Delivery",
    currency: "USD",
    amount: -32.5,
    category: "Food",
    reference: "TXN-2025-003",
    notes: "Pizza delivery",
  },
  {
    id: "txn-007",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 12, 12, 0),
    name: "Grocery Store",
    currency: "GBP",
    amount: -125.42,
    category: "Food",
    reference: "TXN-2025-004",
    notes: "Weekly groceries",
  },
  {
    id: "txn-008",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 11, 13, 15),
    name: "McDonald's",
    currency: "USD",
    amount: -12.99,
    category: "Food",
    reference: "TXN-2025-005",
    notes: "Lunch",
  },
  {
    id: "txn-009",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 10, 7, 45),
    name: "Coffee Shop",
    currency: "GBP",
    amount: -5.75,
    category: "Food",
    reference: "TXN-2025-006",
    notes: "Morning coffee",
  },
  {
    id: "txn-010",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 9, 20, 0),
    name: "Fine Dining Restaurant",
    currency: "USD",
    amount: -185.0,
    category: "Food",
    reference: "TXN-2025-007",
    notes: "Anniversary dinner",
  },

  // January 2025 - Travel Expenses
  {
    id: "txn-011",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 14, 16, 30),
    name: "Uber Ride",
    currency: "USD",
    amount: -28.5,
    category: "Travel",
    reference: "TXN-2025-008",
    notes: "Airport transfer",
  },
  {
    id: "txn-012",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 12, 10, 0),
    name: "Flight Ticket",
    currency: "USD",
    amount: -450.0,
    category: "Travel",
    reference: "TXN-2025-009",
    notes: "New York trip",
  },
  {
    id: "txn-013",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 11, 8, 15),
    name: "Train Ticket",
    currency: "GBP",
    amount: -45.5,
    category: "Travel",
    reference: "TXN-2025-010",
    notes: "London to Manchester",
  },
  {
    id: "txn-014",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 8, 14, 0),
    name: "Gas Station",
    currency: "USD",
    amount: -45.0,
    category: "Travel",
    reference: "TXN-2025-011",
    notes: "Fuel for car",
  },
  {
    id: "txn-015",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 7, 9, 30),
    name: "Parking Fee",
    currency: "GBP",
    amount: -12.0,
    category: "Travel",
    reference: "TXN-2025-012",
    notes: "City center parking",
  },
  {
    id: "txn-016",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 6, 18, 45),
    name: "Hotel Booking",
    currency: "USD",
    amount: -320.0,
    category: "Travel",
    reference: "TXN-2025-013",
    notes: "Weekend getaway",
  },

  // January 2025 - Shopping
  {
    id: "txn-017",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 13, 15, 20),
    name: "Amazon Prime",
    currency: "USD",
    amount: -12.99,
    category: "Shopping",
    reference: "TXN-2025-014",
    notes: "Monthly subscription",
  },
  {
    id: "txn-018",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 12, 11, 0),
    name: "Bookstore Purchase",
    currency: "GBP",
    amount: -24.99,
    category: "Shopping",
    reference: "TXN-2025-015",
    notes: "Technical books",
  },
  {
    id: "txn-019",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 10, 16, 30),
    name: "Electronics Store",
    currency: "USD",
    amount: -299.99,
    category: "Shopping",
    reference: "TXN-2025-016",
    notes: "New headphones",
  },
  {
    id: "txn-020",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 9, 13, 45),
    name: "Clothing Store",
    currency: "GBP",
    amount: -89.5,
    category: "Shopping",
    reference: "TXN-2025-017",
    notes: "Winter jacket",
  },
  {
    id: "txn-021",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 8, 10, 15),
    name: "Online Marketplace",
    currency: "USD",
    amount: -45.99,
    category: "Shopping",
    reference: "TXN-2025-018",
    notes: "Home decor items",
  },

  // January 2025 - Bills
  {
    id: "txn-022",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 5, 8, 0),
    name: "Electricity Bill",
    currency: "GBP",
    amount: -95.6,
    category: "Bills",
    reference: "BILL-2025-001",
    notes: "Monthly bill",
  },
  {
    id: "txn-023",
    account: "Chase",
    timestamp: createTimestamp(2025, 1, 4, 9, 30),
    name: "Netflix Subscription",
    currency: "USD",
    amount: -15.99,
    category: "Bills",
    reference: "TXN-2025-019",
    notes: "Monthly subscription",
  },
  {
    id: "txn-024",
    account: "Monzo",
    timestamp: createTimestamp(2025, 1, 3, 7, 0),
    name: "Internet Bill",
    currency: "GBP",
    amount: -29.99,
    category: "Bills",
    reference: "BILL-2025-002",
    notes: "Monthly broadband",
  },
  {
    id: "txn-025",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 2, 10, 0),
    name: "Phone Bill",
    currency: "USD",
    amount: -65.0,
    category: "Bills",
    reference: "BILL-2025-003",
    notes: "Monthly mobile plan",
  },
  {
    id: "txn-026",
    account: "Barclays",
    timestamp: createTimestamp(2025, 1, 1, 8, 30),
    name: "Gas Bill",
    currency: "GBP",
    amount: -78.5,
    category: "Bills",
    reference: "BILL-2025-004",
    notes: "Monthly gas bill",
  },

  // December 2024 - Income
  {
    id: "txn-027",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 28, 14, 0),
    name: "Freelance Payment",
    currency: "USD",
    amount: 1500.0,
    category: "Other",
    reference: "INV-2024-001",
    notes: "Web development project",
  },
  {
    id: "txn-028",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 20, 9, 0),
    name: "Salary Deposit",
    currency: "GBP",
    amount: 3500.0,
    category: "Other",
    reference: "SAL-2024-012",
    notes: "Monthly salary",
  },

  // December 2024 - Food Expenses
  {
    id: "txn-029",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 31, 21, 0),
    name: "New Year's Eve Dinner",
    currency: "USD",
    amount: -125.0,
    category: "Food",
    reference: "TXN-2024-999",
    notes: "Celebration dinner",
  },
  {
    id: "txn-030",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 30, 12, 30),
    name: "Christmas Groceries",
    currency: "GBP",
    amount: -185.75,
    category: "Food",
    reference: "TXN-2024-998",
    notes: "Holiday shopping",
  },
  {
    id: "txn-031",
    account: "American Express",
    timestamp: createTimestamp(2024, 12, 29, 19, 0),
    name: "Restaurant",
    currency: "USD",
    amount: -95.0,
    category: "Food",
    reference: "TXN-2024-997",
    notes: "Family dinner",
  },
  {
    id: "txn-032",
    account: "Barclays",
    timestamp: createTimestamp(2024, 12, 28, 8, 0),
    name: "Coffee Shop",
    currency: "GBP",
    amount: -4.25,
    category: "Food",
    reference: "TXN-2024-996",
    notes: "Morning coffee",
  },
  {
    id: "txn-033",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 27, 13, 45),
    name: "Fast Food",
    currency: "USD",
    amount: -18.5,
    category: "Food",
    reference: "TXN-2024-995",
    notes: "Lunch",
  },

  // December 2024 - Travel Expenses
  {
    id: "txn-034",
    account: "American Express",
    timestamp: createTimestamp(2024, 12, 29, 11, 10),
    name: "Train Ticket",
    currency: "EUR",
    amount: -78.5,
    category: "Travel",
    reference: "TXN-2024-994",
    notes: "London to Paris",
  },
  {
    id: "txn-035",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 26, 15, 20),
    name: "Uber Ride",
    currency: "GBP",
    amount: -22.5,
    category: "Travel",
    reference: "TXN-2024-993",
    notes: "City center",
  },
  {
    id: "txn-036",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 25, 10, 0),
    name: "Flight Ticket",
    currency: "USD",
    amount: -520.0,
    category: "Travel",
    reference: "TXN-2024-992",
    notes: "Holiday trip",
  },
  {
    id: "txn-037",
    account: "Barclays",
    timestamp: createTimestamp(2024, 12, 24, 9, 30),
    name: "Parking Fee",
    currency: "GBP",
    amount: -15.0,
    category: "Travel",
    reference: "TXN-2024-991",
    notes: "Shopping center",
  },

  // December 2024 - Shopping
  {
    id: "txn-038",
    account: "American Express",
    timestamp: createTimestamp(2024, 12, 23, 16, 0),
    name: "Christmas Shopping",
    currency: "USD",
    amount: -350.0,
    category: "Shopping",
    reference: "TXN-2024-990",
    notes: "Gift purchases",
  },
  {
    id: "txn-039",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 22, 14, 30),
    name: "Bookstore",
    currency: "GBP",
    amount: -35.99,
    category: "Shopping",
    reference: "TXN-2024-989",
    notes: "Holiday reading",
  },
  {
    id: "txn-040",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 21, 11, 15),
    name: "Electronics Store",
    currency: "USD",
    amount: -199.99,
    category: "Shopping",
    reference: "TXN-2024-988",
    notes: "Gadget purchase",
  },

  // December 2024 - Bills
  {
    id: "txn-041",
    account: "Barclays",
    timestamp: createTimestamp(2024, 12, 27, 8, 30),
    name: "Gas Bill",
    currency: "GBP",
    amount: -95.6,
    category: "Bills",
    reference: "BILL-2024-999",
    notes: "December bill",
  },
  {
    id: "txn-042",
    account: "Chase",
    timestamp: createTimestamp(2024, 12, 20, 9, 0),
    name: "Streaming Service",
    currency: "USD",
    amount: -9.99,
    category: "Bills",
    reference: "TXN-2024-987",
    notes: "Monthly subscription",
  },
  {
    id: "txn-043",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 19, 7, 0),
    name: "Water Bill",
    currency: "GBP",
    amount: -45.2,
    category: "Bills",
    reference: "BILL-2024-998",
    notes: "Quarterly bill",
  },

  // November 2024 - Income
  {
    id: "txn-044",
    account: "Monzo",
    timestamp: createTimestamp(2024, 11, 20, 9, 0),
    name: "Salary Deposit",
    currency: "GBP",
    amount: 3500.0,
    category: "Other",
    reference: "SAL-2024-011",
    notes: "Monthly salary",
  },
  {
    id: "txn-045",
    account: "American Express",
    timestamp: createTimestamp(2024, 11, 15, 14, 30),
    name: "Consulting Fee",
    currency: "USD",
    amount: 2000.0,
    category: "Other",
    reference: "INV-2024-002",
    notes: "Business consulting",
  },

  // November 2024 - Food Expenses
  {
    id: "txn-046",
    account: "Barclays",
    timestamp: createTimestamp(2024, 11, 28, 18, 30),
    name: "Restaurant",
    currency: "GBP",
    amount: -75.0,
    category: "Food",
    reference: "TXN-2024-986",
    notes: "Dinner out",
  },
  {
    id: "txn-047",
    account: "Chase",
    timestamp: createTimestamp(2024, 11, 25, 12, 0),
    name: "Grocery Store",
    currency: "USD",
    amount: -145.5,
    category: "Food",
    reference: "TXN-2024-985",
    notes: "Weekly groceries",
  },
  {
    id: "txn-048",
    account: "Monzo",
    timestamp: createTimestamp(2024, 11, 22, 8, 15),
    name: "Coffee Shop",
    currency: "GBP",
    amount: -5.5,
    category: "Food",
    reference: "TXN-2024-984",
    notes: "Morning coffee",
  },
  {
    id: "txn-049",
    account: "American Express",
    timestamp: createTimestamp(2024, 11, 20, 19, 45),
    name: "Food Delivery",
    currency: "USD",
    amount: -42.99,
    category: "Food",
    reference: "TXN-2024-983",
    notes: "Dinner delivery",
  },

  // November 2024 - Travel Expenses
  {
    id: "txn-050",
    account: "Chase",
    timestamp: createTimestamp(2024, 11, 18, 10, 0),
    name: "Flight Ticket",
    currency: "USD",
    amount: -380.0,
    category: "Travel",
    reference: "TXN-2024-982",
    notes: "Business trip",
  },
  {
    id: "txn-051",
    account: "Monzo",
    timestamp: createTimestamp(2024, 11, 15, 14, 30),
    name: "Train Ticket",
    currency: "GBP",
    amount: -52.0,
    category: "Travel",
    reference: "TXN-2024-981",
    notes: "Weekend trip",
  },
  {
    id: "txn-052",
    account: "Barclays",
    timestamp: createTimestamp(2024, 11, 12, 9, 0),
    name: "Uber Ride",
    currency: "GBP",
    amount: -18.5,
    category: "Travel",
    reference: "TXN-2024-980",
    notes: "Airport",
  },
  {
    id: "txn-053",
    account: "American Express",
    timestamp: createTimestamp(2024, 11, 10, 16, 45),
    name: "Hotel Booking",
    currency: "USD",
    amount: -280.0,
    category: "Travel",
    reference: "TXN-2024-979",
    notes: "Weekend stay",
  },

  // November 2024 - Shopping
  {
    id: "txn-054",
    account: "Chase",
    timestamp: createTimestamp(2024, 11, 25, 15, 30),
    name: "Online Store",
    currency: "USD",
    amount: -89.99,
    category: "Shopping",
    reference: "TXN-2024-978",
    notes: "Black Friday deal",
  },
  {
    id: "txn-055",
    account: "Monzo",
    timestamp: createTimestamp(2024, 11, 23, 11, 0),
    name: "Clothing Store",
    currency: "GBP",
    amount: -125.0,
    category: "Shopping",
    reference: "TXN-2024-977",
    notes: "Winter clothes",
  },
  {
    id: "txn-056",
    account: "Barclays",
    timestamp: createTimestamp(2024, 11, 20, 13, 15),
    name: "Electronics Store",
    currency: "GBP",
    amount: -450.0,
    category: "Shopping",
    reference: "TXN-2024-976",
    notes: "New laptop",
  },

  // November 2024 - Bills
  {
    id: "txn-057",
    account: "Barclays",
    timestamp: createTimestamp(2024, 11, 5, 8, 0),
    name: "Electricity Bill",
    currency: "GBP",
    amount: -95.6,
    category: "Bills",
    reference: "BILL-2024-997",
    notes: "Monthly bill",
  },
  {
    id: "txn-058",
    account: "Chase",
    timestamp: createTimestamp(2024, 11, 4, 9, 30),
    name: "Netflix Subscription",
    currency: "USD",
    amount: -15.99,
    category: "Bills",
    reference: "TXN-2024-975",
    notes: "Monthly subscription",
  },
  {
    id: "txn-059",
    account: "Monzo",
    timestamp: createTimestamp(2024, 11, 3, 7, 0),
    name: "Internet Bill",
    currency: "GBP",
    amount: -29.99,
    category: "Bills",
    reference: "BILL-2024-996",
    notes: "Monthly broadband",
  },
  {
    id: "txn-060",
    account: "American Express",
    timestamp: createTimestamp(2024, 11, 2, 10, 0),
    name: "Phone Bill",
    currency: "USD",
    amount: -65.0,
    category: "Bills",
    reference: "BILL-2024-995",
    notes: "Monthly mobile plan",
  },

  // October 2024 - Income
  {
    id: "txn-061",
    account: "Monzo",
    timestamp: createTimestamp(2024, 10, 20, 9, 0),
    name: "Salary Deposit",
    currency: "GBP",
    amount: 3500.0,
    category: "Other",
    reference: "SAL-2024-010",
    notes: "Monthly salary",
  },
  {
    id: "txn-062",
    account: "Chase",
    timestamp: createTimestamp(2024, 10, 12, 14, 0),
    name: "Freelance Payment",
    currency: "USD",
    amount: 900.0,
    category: "Other",
    reference: "INV-2024-003",
    notes: "Design project",
  },

  // October 2024 - Food Expenses
  {
    id: "txn-063",
    account: "Barclays",
    timestamp: createTimestamp(2024, 10, 28, 19, 0),
    name: "Restaurant",
    currency: "GBP",
    amount: -95.0,
    category: "Food",
    reference: "TXN-2024-974",
    notes: "Birthday dinner",
  },
  {
    id: "txn-064",
    account: "Chase",
    timestamp: createTimestamp(2024, 10, 25, 12, 30),
    name: "Grocery Store",
    currency: "USD",
    amount: -135.75,
    category: "Food",
    reference: "TXN-2024-973",
    notes: "Weekly groceries",
  },
  {
    id: "txn-065",
    account: "Monzo",
    timestamp: createTimestamp(2024, 10, 22, 8, 0),
    name: "Coffee Shop",
    currency: "GBP",
    amount: -4.5,
    category: "Food",
    reference: "TXN-2024-972",
    notes: "Morning coffee",
  },

  // October 2024 - Travel Expenses
  {
    id: "txn-066",
    account: "American Express",
    timestamp: createTimestamp(2024, 10, 18, 11, 0),
    name: "Flight Ticket",
    currency: "USD",
    amount: -420.0,
    category: "Travel",
    reference: "TXN-2024-971",
    notes: "Business travel",
  },
  {
    id: "txn-067",
    account: "Monzo",
    timestamp: createTimestamp(2024, 10, 15, 15, 30),
    name: "Train Ticket",
    currency: "GBP",
    amount: -48.5,
    category: "Travel",
    reference: "TXN-2024-970",
    notes: "Day trip",
  },

  // October 2024 - Shopping
  {
    id: "txn-068",
    account: "Chase",
    timestamp: createTimestamp(2024, 10, 25, 16, 0),
    name: "Amazon Purchase",
    currency: "USD",
    amount: -75.99,
    category: "Shopping",
    reference: "TXN-2024-969",
    notes: "Home items",
  },
  {
    id: "txn-069",
    account: "Barclays",
    timestamp: createTimestamp(2024, 10, 23, 10, 30),
    name: "Bookstore",
    currency: "GBP",
    amount: -28.99,
    category: "Shopping",
    reference: "TXN-2024-968",
    notes: "New books",
  },

  // October 2024 - Bills
  {
    id: "txn-070",
    account: "Barclays",
    timestamp: createTimestamp(2024, 10, 5, 8, 0),
    name: "Electricity Bill",
    currency: "GBP",
    amount: -95.6,
    category: "Bills",
    reference: "BILL-2024-994",
    notes: "Monthly bill",
  },
  {
    id: "txn-071",
    account: "Chase",
    timestamp: createTimestamp(2024, 10, 4, 9, 30),
    name: "Streaming Service",
    currency: "USD",
    amount: -9.99,
    category: "Bills",
    reference: "TXN-2024-967",
    notes: "Monthly subscription",
  },

  // Transaction with subTransactions (for testing expandable rows)
  {
    id: "txn-072",
    account: "American Express",
    timestamp: createTimestamp(2025, 1, 16, 10, 0),
    name: "Split Payment - Group Dinner",
    currency: "USD",
    amount: -250.0,
    category: "Food",
    reference: "TXN-2025-020",
    notes: "Split bill with friends",
    subTransactions: [
      {
        id: "txn-072-1",
        account: "American Express",
        timestamp: createTimestamp(2025, 1, 16, 10, 0),
        name: "My portion - Group Dinner",
        currency: "USD",
        amount: -85.0,
        category: "Food",
        reference: "TXN-2025-020-1",
        notes: "My share",
      },
      {
        id: "txn-072-2",
        account: "American Express",
        timestamp: createTimestamp(2025, 1, 16, 10, 0),
        name: "Friend 1 portion - Group Dinner",
        currency: "USD",
        amount: -82.5,
        category: "Food",
        reference: "TXN-2025-020-2",
        notes: "Friend 1 share",
      },
      {
        id: "txn-072-3",
        account: "American Express",
        timestamp: createTimestamp(2025, 1, 16, 10, 0),
        name: "Friend 2 portion - Group Dinner",
        currency: "USD",
        amount: -82.5,
        category: "Food",
        reference: "TXN-2025-020-3",
        notes: "Friend 2 share",
      },
    ],
  },
  {
    id: "txn-073",
    account: "Monzo",
    timestamp: createTimestamp(2024, 12, 15, 14, 30),
    name: "Split Payment - Vacation",
    currency: "GBP",
    amount: -1200.0,
    category: "Travel",
    reference: "TXN-2024-986",
    notes: "Shared vacation expenses",
    subTransactions: [
      {
        id: "txn-073-1",
        account: "Monzo",
        timestamp: createTimestamp(2024, 12, 15, 14, 30),
        name: "My portion - Vacation",
        currency: "GBP",
        amount: -400.0,
        category: "Travel",
        reference: "TXN-2024-986-1",
        notes: "My share",
      },
      {
        id: "txn-073-2",
        account: "Monzo",
        timestamp: createTimestamp(2024, 12, 15, 14, 30),
        name: "Partner portion - Vacation",
        currency: "GBP",
        amount: -400.0,
        category: "Travel",
        reference: "TXN-2024-986-2",
        notes: "Partner share",
      },
      {
        id: "txn-073-3",
        account: "Monzo",
        timestamp: createTimestamp(2024, 12, 15, 14, 30),
        name: "Shared expenses - Vacation",
        currency: "GBP",
        amount: -400.0,
        category: "Travel",
        reference: "TXN-2024-986-3",
        notes: "Shared portion",
      },
    ],
  },
];
