import { Transaction } from "./columns";

// This would normally come from a database/API
export function getAllTransactions(): Transaction[] {
  return [
    {
      id: "txn-001",
      account: "Monzo",
      timestamp: "2025-01-15 14:32:00",
      name: "Starbucks Coffee",
      currency: "GBP",
      amount: -4.5,
      category: "Food",
      reference: "TXN-2025-001",
      notes: "Morning coffee",
    },
    {
      id: "txn-002",
      account: "Chase",
      timestamp: "2025-01-14 18:45:00",
      name: "Amazon Prime",
      currency: "USD",
      amount: -12.99,
      category: "Shopping",
      reference: "TXN-2025-002",
      notes: "Monthly subscription",
    },
    {
      id: "txn-003",
      account: "American Express",
      timestamp: "2025-01-13 20:15:00",
      name: "Uber Ride",
      currency: "USD",
      amount: -28.5,
      category: "Travel",
      reference: "TXN-2025-003",
      notes: "Airport transfer",
    },
    {
      id: "txn-004",
      account: "Monzo",
      timestamp: "2025-01-12 12:00:00",
      name: "Salary Deposit",
      currency: "GBP",
      amount: 3500.0,
      category: "Other",
      reference: "SAL-2025-001",
      notes: "Monthly salary",
    },
    {
      id: "txn-005",
      account: "Barclays",
      timestamp: "2025-01-11 09:30:00",
      name: "Grocery Store",
      currency: "GBP",
      amount: -85.42,
      category: "Food",
      reference: "TXN-2025-005",
      notes: "Weekly groceries",
    },
    {
      id: "txn-006",
      account: "Chase",
      timestamp: "2025-01-10 15:20:00",
      name: "Netflix Subscription",
      currency: "USD",
      amount: -15.99,
      category: "Bills",
      reference: "TXN-2025-006",
      notes: "Monthly subscription",
    },
    {
      id: "txn-007",
      account: "American Express",
      timestamp: "2025-01-09 19:00:00",
      name: "Restaurant Dinner",
      currency: "USD",
      amount: -125.0,
      category: "Food",
      reference: "TXN-2025-007",
      notes: "Anniversary dinner",
    },
    {
      id: "txn-008",
      account: "Monzo",
      timestamp: "2025-01-08 11:15:00",
      name: "Freelance Payment",
      currency: "GBP",
      amount: 800.0,
      category: "Other",
      reference: "INV-2025-001",
      notes: "Web development project",
    },
    {
      id: "txn-009",
      account: "Barclays",
      timestamp: "2025-01-07 08:00:00",
      name: "Electricity Bill",
      currency: "GBP",
      amount: -95.6,
      category: "Bills",
      reference: "BILL-2025-001",
      notes: "Monthly bill",
    },
    {
      id: "txn-010",
      account: "Chase",
      timestamp: "2025-01-06 16:45:00",
      name: "Gas Station",
      currency: "USD",
      amount: -45.0,
      category: "Travel",
      reference: "TXN-2025-010",
      notes: "Fuel for car",
    },
    {
      id: "txn-011",
      account: "American Express",
      timestamp: "2025-01-05 13:30:00",
      name: "Bookstore",
      currency: "USD",
      amount: -32.99,
      category: "Shopping",
      reference: "TXN-2025-011",
      notes: "Birthday celebration",
    },
    {
      id: "txn-012",
      account: "Chase",
      timestamp: "2025-01-04 14:00:00",
      name: "Flight Ticket",
      currency: "USD",
      amount: -450.0,
      category: "Travel",
      reference: "TXN-2025-012",
      notes: "New York trip",
    },
    {
      id: "txn-013",
      account: "American Express",
      timestamp: "2025-01-03 10:45:00",
      name: "Gym Membership",
      currency: "USD",
      amount: -49.99,
      category: "Other",
      reference: "TXN-2025-013",
      notes: "Monthly fee",
    },
    {
      id: "txn-014",
      account: "Monzo",
      timestamp: "2025-01-02 17:30:00",
      name: "Coffee Shop",
      currency: "GBP",
      amount: -5.75,
      category: "Food",
      reference: "TXN-2025-014",
      notes: "Afternoon break",
    },
    {
      id: "txn-015",
      account: "Barclays",
      timestamp: "2025-01-01 09:00:00",
      name: "Internet Bill",
      currency: "GBP",
      amount: -29.99,
      category: "Bills",
      reference: "BILL-2025-003",
      notes: "Monthly broadband",
    },
    {
      id: "txn-016",
      account: "Chase",
      timestamp: "2024-12-31 21:00:00",
      name: "New Year's Eve Dinner",
      currency: "USD",
      amount: -125.0,
      category: "Food",
      reference: "TXN-2024-999",
      notes: "Celebration dinner",
    },
    {
      id: "txn-017",
      account: "Monzo",
      timestamp: "2024-12-30 15:20:00",
      name: "Bookstore Purchase",
      currency: "GBP",
      amount: -24.99,
      category: "Shopping",
      reference: "TXN-2024-998",
      notes: "Technical books",
    },
    {
      id: "txn-018",
      account: "American Express",
      timestamp: "2024-12-29 11:10:00",
      name: "Train Ticket",
      currency: "EUR",
      amount: -78.5,
      category: "Travel",
      reference: "TXN-2024-997",
      notes: "London to Paris",
    },
    {
      id: "txn-019",
      account: "Chase",
      timestamp: "2024-12-28 16:45:00",
      name: "Freelance Payment",
      currency: "USD",
      amount: 1200.0,
      category: "Other",
      reference: "INV-2024-001",
      notes: "Web development project",
    },
    {
      id: "txn-020",
      account: "Barclays",
      timestamp: "2024-12-27 08:30:00",
      name: "Gas Bill",
      currency: "GBP",
      amount: -95.6,
      category: "Bills",
      reference: "BILL-2024-999",
      notes: "December bill",
    },
  ];
}

// Helper to flatten transactions including sub-transactions
export function flattenTransactions(
  transactions: Transaction[],
): Transaction[] {
  const flattened: Transaction[] = [];

  function addTransaction(txn: Transaction) {
    flattened.push(txn);
    if (txn.subTransactions) {
      txn.subTransactions.forEach(addTransaction);
    }
  }

  transactions.forEach(addTransaction);
  return flattened;
}
